### ISSUE TITLE
エンドポイント

### ISSUE THREAD

**Issue by tsubame-misa** [satorunooshie/fireworks_stall#9]
ログイン：/login
作る：/make
打ち上げ：/setup
得点：/score

**Comment by satorunooshie** [comment]
signup -> post
DB save

**Comment by satorunooshie** [comment]
/getLevel -> get
DB select

/score -> post
DB save

/ranking/list -> get
DB select

**Comment by satorunooshie** [comment]
`Authorization: Bearer xxxx`

**Comment by satorunooshie** [comment]
user jwt token

**Comment by satorunooshie** [comment]
username, userID

**Comment by satorunooshie** [comment]
score mentorに相談
-> jsonのresponse
